### ISSUE TITLE
ES crashes if gamelist is too long in Chinese or Japanese with character/kanji.

### ISSUE THREAD

**Issue by SumavisionQ5** [batocera-linux/batocera-emulationstation#213] opened 2019-10-11 06:23 UTC
This issue also happens in RetroPie ES. But I think it's better to open an issue here since Batocera supports Chinese without any extra operation. If users use a long game list with over 2K or so games, and if game list is in Chinese or Japanese with many many characters coded in 3 bytes, ES would crash when scrolling down the game list for a little longer. The higer resolution is, the sooner ES crashes. ES just quits with SIGSEV signal.
`ERROR    Interrupt signal SIGSEGV received.`
Maybe there is a memory leakage on font caching?

**Comment by fabricecaruso** [comment] 2019-10-15 15:45
I'm sorry but I'm not Chinese, and I don't have big gamelists in Chinese...
I can't help without it.

**Comment by shantigilbert** [comment] 2019-10-15 17:30
If you have a full mame set is rather easy to set it in Chinese, I can. Send the files needed (I am also not Chinese but I tested this bug)

**Comment by nadenislamarre** [comment] 2019-10-16 10:11
i've not a such set.
but an easy way is to replace files by empty files with the same name in roms while the content is not necessary to es and zip the result.

**Comment by shantigilbert** [comment] 2019-10-16 15:35
That could work, here are the files needed [cn_mame.zip](https://github.com/batocera-linux/batocera-emulationstation/files/3735115/cn_mame.zip), the mamenames.xml goes into the resources folder and the gamelist.xml is for the roms/arcade (might work on others with \<platform>arcade\</platform>)

**Comment by shantigilbert** [comment] 2019-10-23 06:03
More info on this issue, I compiled a debug version and I ran gdb on it this is the result:

```
Thread 1 "emulationstatio" received signal SIGSEGV, Segmentation fault.
0x005be074 in Font::renderTextCache (this=0x1832b20, cache=0x29ae6e0) at ../es-core/src/resources/Font.cpp:441
441	../es-core/src/resources/Font.cpp: No such file or directory.
(gdb) bt
#0  0x005be074 in Font::renderTextCache (this=0x1832b20, cache=0x29ae6e0) at ../es-core/src/resources/Font.cpp:441
#1  0x0042c464 in TextListComponent<FileData*>::render (this=0x182f6d4, parentTrans=...) at ../es-app/src/components/TextListComponent.h:235
#2  0x00504ea8 in GuiComponent::renderChildren (this=0x182f218, transform=...) at ../es-core/src/GuiComponent.cpp:75
#3  0x00437774 in IGameListView::render (this=0x182f218, parentTrans=...) at ../es-app/src/views/gamelist/IGameListView.cpp:57
#4  0x004686f8 in ViewController::render (this=0xa92e88, parentTrans=...) at ../es-app/src/views/ViewController.cpp:539
#5  0x00550594 in Window::render (this=0xffd0ba3c) at ../es-core/src/Window.cpp:453
#6  0x002a6f98 in main (argc=1, argv=0xffd0c714) at ../es-app/src/main.cpp:598
```
Hopefully it can help

**Comment by fabricecaruso** [comment] 2019-10-23 15:52
Thanks, so : probably due to the fact a Glyph is not found anywhere in fonts.
As I can't reproduce : I "try" a fix to avoid assertion and continue without drawing in this case.

**Comment by shantigilbert** [comment] 2019-10-23 16:02
I noticed this error is when you are fast scrolling and the current letter pair is shown on the dimmed screen. Maybe there is a way to ignore displaying the Glyph if it doesn't exists? 

Let me know if you need anything else to debug/test

**Comment by shantigilbert** [comment] 2019-10-23 18:49
@fabricecaruso I applied your patch (from your PR) and unfortunately (and weirdly) It is still the exact same error:

```
Thread 1 "emulationstatio" received signal SIGSEGV, Segmentation fault.
Font::renderTextCache (this=0x19e1e48, cache=0x2b36140) at ../es-core/src/resources/Font.cpp:441
441	../es-core/src/resources/Font.cpp: No such file or directory.
(gdb) bt
#0  Font::renderTextCache (this=0x19e1e48, cache=0x2b36140) at ../es-core/src/resources/Font.cpp:441
#1  0x0042c6fc in TextListComponent<FileData*>::render (this=0x284df1c, parentTrans=...) at ../es-app/src/components/TextListComponent.h:235
#2  0x00505140 in GuiComponent::renderChildren (this=0x284da60, transform=...) at ../es-core/src/GuiComponent.cpp:75
#3  0x00437a0c in IGameListView::render (this=0x284da60, parentTrans=...) at ../es-app/src/views/gamelist/IGameListView.cpp:57
#4  0x00468990 in ViewController::render (this=0xc46f10, parentTrans=...) at ../es-app/src/views/ViewController.cpp:539
#5  0x0055082c in Window::render (this=0xff9d5b0c) at ../es-core/src/Window.cpp:453
#6  0x002a6f98 in main (argc=1, argv=0xff9d67e4) at ../es-app/src/main.cpp:598
```

**Comment by fabricecaruso** [comment] 2019-10-25 09:04
Honestly, this one was crazy to find...
This should be fixed ( see the commit in my "fix" branch ) & soon be merged.

**Closed** 2019-10-25 09:10 UTC

**Comment by shantigilbert** [comment] 2019-10-25 16:11
@fabricecaruso Thank you!

**Comment by shantigilbert** [comment] 2019-10-25 17:43
@fabricecaruso after testing the fix, altho it does not crash anymore it seems the fonts go crazy. Here is a video to demonstrate the problem

https://youtu.be/z1QFgPV4B1s

(I only tested the one commit that fixed the issue, not sure if I need the others as well)

**Comment by Darknior** [comment] 2019-10-25 18:18
WOAW very impressive in action this bug !!!

**Comment by fabricecaruso** [comment] 2019-10-25 18:49
Still better than a crash.... And very very very very very hard to debug ( try it.... )
1,386 billion people in china, no one to help debug it ????

**Comment by shantigilbert** [comment] 2019-10-25 18:53
even tho I am not Chinese I wish I knew how to debug it so I could help more :( I can imagine is a nightmare to debug since its a very weird bug.

**Comment by fabricecaruso** [comment] 2019-10-25 18:57
> I can imagine is a nightmare to debug

Yes it is ! & I have some other priorities

**Comment by shantigilbert** [comment] 2019-10-25 19:28
Then I assume it would be better to revert this fix? , until someone could help you more on this issue since once it happens the only way to recover the fonts is to restart ES

**Comment by fabricecaruso** [comment] 2019-10-25 19:49
Why... ? It avoids a crash....

**Comment by shantigilbert** [comment] 2019-10-25 20:06
Yes, I think your fix is on the right direction, but If you notice in the video, once the error happens all text disappears, not just Chinese characters, its only fixed with an ES restart.

**Comment by fabricecaruso** [comment] 2019-10-25 20:37
The "i++;" is absolutely necessary... Why revert this ? If we revert this, the day we'll do more debugging we'll loose time searching for the "i++" again....

**Comment by shantigilbert** [comment] 2019-10-25 20:41
You are right, this can lead for easier debugging in the future without worrying about that part.

I hardly know anything about C++ so what I say its just opinions on the matter, just trying to help and reduce the workload. 

But really, thanks for your hard work on this I appreciate it.
