### ISSUE TITLE
v32dev 15.08.2021 on pi4 Memory leak ando low memory free

### ISSUE THREAD

**Issue by chippettone** [batocera-linux/batocera-emulationstation#954] opened 2021-08-23 06:03 UTC
The problem reported, time ago, still is present in this version of Batocera. Practically scrolling images in EmulationStation, the memory is gradually filled but never cleaned. In the 2GB version it creates blocks for poor memory. The cache should be cleaned in EmulationStation every time you change emulator or leave a game. Also because the cache is occupied by scrolling the images of the scrape.

**Comment by Redemp** [comment] 2021-08-23 06:14
I can confirm that the issue is not only on Raspberry Pi but on x86_64.

**Comment by nadenislamarre** [comment] 2021-08-24 05:41
hi, can you tell me the size of the vram value in menu > system > developpers options ?
this value limits the ram usage during scrolling. works here.

**Comment by chippettone** [comment] 2021-08-28 10:48
Standard value of Vram.

**Comment by henriquemenino** [comment] 2021-09-03 14:52
Hello I did several tests analyzing this problem and reported the results in the posts:
https://forum.batocera.org/d/6197-ram-memory-management-v30v31
https://forum.recalbox.com/topic/24819/gerenciamento-de-mem%C3%B3ria-ram-v7-2-2-em-pi4

If you need me to do more tests on Pi4 you can count on me.

**Comment by henriquemenino** [comment] 2021-09-09 11:35
Today I tested the  V32 beta version without Scrap images and videos, just opening and closing the games and the problem persists.

**Comment by Hew-ux** [comment] 2021-10-21 05:00
Here's the equivalent issue on Batocera-linux repo: https://github.com/batocera-linux/batocera.linux/issues/4680

**Closed** 2023-11-03 10:23 UTC
Labels: Related to batocera.linux
